language: go

go:
  - "1.13.x"

env:
  global:
    - GO111MODULE=on

branches:
  only:
    - develop

jobs:
  include:
    - stage: test
      name: unitTests1
      script:
        - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip -d /home/travis/
        - export webdriverPath=/home/travis/chromedriver
        - export PATH=$PATH:/home/travis/
        - sudo apt-get install -y libgconf-2-4
        - echo $PATH
        - cd /home/travis/
        - ls
        - cd
        - ls
        - go test -run TestAdd
    - script:
      - go test -run TestRemove
      - cd /home/travis
      - ls
      name: unitTests2
    - stage: deploy
      provider: script
      script:
        - echo 'deploy stage is not implemented yet'
        - cd /home/travis/
        - ls

notifications:
  email: false