language: go

go:
  - "1.13.x"

env:
  global:
    - GO111MODULE=on

branches:
  only:
    - develop

stages:
  - setupEnvironment
  - test
  - deploy

jobs:
  include:
    - setupEnvironment:
      script:
        - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip -d /home/travis/
        - export webdriverPath=/home/travis/chromedriver
        - export PATH=$PATH:/home/travis/
        - sudo apt-get install -y libgconf-2-4
        - echo $PATH
        - cd $webdriverPath
        - ls
    - test:
      script: go test
    - deploy:
      provider: script
      script:
        -echo 'deploy stage is not implemented yet'

notifications:
  email: false